### ISSUE TITLE
Minimize on close

### ISSUE THREAD

**Issue by dmitrybabich** [I-Info/BingLite#3]
Is this possible to add the Minimize on Close functionality? So that clicking on the close button would minimize the app instead? This would speed up the app launching when using frequiently.

**Comment by I-Info** [comment]
Yes, it's possible to. But I didn't know exactly which type of Minimization should be performed for your feature requirement. Like using the systray in the menu or keeping it running on the macOS dock (showing the window after clicking the app icon)?

**Comment by dmitrybabich** [comment]
For me, any of these approaches would be fine. I just want the app to open immediately to avoid waiting for the page to load.
